services:
  db:
    container_name: techfix_db
    image: postgres:16
    environment:
      POSTGRES_DB: techfix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
     - ./database:/docker-entrypoint-initdb.d
     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
